alias sudo='sudo '
alias mntwin='mount /dev/nvme0n1p3 /mnt/windows'
alias ls='ls --color=auto -tr'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias py='python'
alias eb='v ~/.bashrc'
alias ex='v ~/.xmonad/xmonad.hs'
alias clip='xclip -selection c'
alias headphones='bluetoothctl connect F4:4E:FD:00:94:8E'
alias headphones_dc='bluetoothctl disconnect F4:4E:FD:00:94:8E'
alias battery='acpi'
alias config='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias sb='source ~/.bashrc'
alias startdocker='systemctl start docker'
eval $(thefuck --alias fuck) # This is prescribed by the thefuck docs
alias wifi='nmcli dev wifi'
alias uciwifi='wifi connect "UCInet Mobile Access"'
alias cleartrash='rm -rf /home/eric/.local/share/Trash'
alias dronewifi='wifi connect TXMOD-EA-64-42'
alias plazawifi='wifi connect PlazaVerde-MyCampusNet'
alias p='py'
alias t='tmux'
alias pio='/home/eric/.platformio/penv/bin/platformio'
